# Autogenerated wrapper script for LibTorchCAPI_jll for x86_64-linux-gnu-cxx11
export libtorch_capi

JLLWrappers.@generate_wrapper_header("LibTorchCAPI")
JLLWrappers.@declare_library_product(libtorch_capi, "libtorch_capi.so")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libtorch_capi,
        "lib/libtorch_capi.so",
        nothing,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
